In [1]:
import numpy as np

TimeSoftmaxWithLossクラスのbackwardの動作チェック

In [15]:
N = 10 # batch_size
T = 25 # Time Series
V = 100 # Vocabrary Size

In [20]:
rand = np.random.rand
ys = rand(N*T, V)
print(ys.shape)
ys

(250, 100)


array([[0.32369525, 0.16740833, 0.67888323, ..., 0.86936893, 0.56004131,
        0.35806248],
       [0.48212304, 0.47810808, 0.29029196, ..., 0.2498677 , 0.24883379,
        0.12674593],
       [0.76913456, 0.86462755, 0.74193495, ..., 0.9186964 , 0.05698265,
        0.74491183],
       ...,
       [0.69619853, 0.73751779, 0.60706965, ..., 0.16787814, 0.19703047,
        0.79757076],
       [0.2488049 , 0.29018982, 0.28183681, ..., 0.7890609 , 0.45471831,
        0.42634751],
       [0.23807979, 0.59072604, 0.48827377, ..., 0.054286  , 0.80113962,
        0.56755198]])

In [21]:
ys_sum = ys.sum(axis=1)
ys_sum.shape

(250,)

In [23]:
ys_prob = ys / ys_sum[:, np.newaxis]
print(ys_prob.shape)
ys_prob

(250, 100)


array([[0.00691196, 0.00357472, 0.0144964 , ..., 0.0185639 , 0.01195873,
        0.00764582],
       [0.01035885, 0.01027258, 0.00623718, ..., 0.00536863, 0.00534642,
        0.00272325],
       [0.01424866, 0.01601772, 0.01374477, ..., 0.01701938, 0.00105564,
        0.01379992],
       ...,
       [0.01436486, 0.01521741, 0.01252584, ..., 0.00346388, 0.00406539,
        0.0164565 ],
       [0.00504435, 0.0058834 , 0.00571405, ..., 0.01599768, 0.00921911,
        0.00864391],
       [0.00491312, 0.01219049, 0.01007624, ..., 0.00112027, 0.01653268,
        0.01171226]])

In [27]:
ys_label = np.argmax(ys_prob, axis=1)
print(ys_label.shape)
print(ys_label[:10])
print(np.max(ys_label))

(250,)
[17  7 51 12 36 77 41 88 64 83]
99


In [40]:
ts = np.random.uniform(size=(N*T,), low=0.0, high=99.9).astype(np.int64)
print("ts.shape", ts.shape)
# print(ts) 
dx = np.copy(ys_prob)
dx[np.arange(N*T), ts] -= 1
print("dx.shape", dx.shape)

ignore_label = 0 # 仮にid:0を無効ラベルとする
mask = (ts != ignore_label)
print("mask.shape", mask.shape)
print("mask[:3]", mask[:3])

ts.shape (250,)
dx.shape (250, 100)
mask.shape (250,)
mask[:3] [ True  True  True]


In [41]:
mask_sum = mask.sum()
print("mask_sum", mask_sum)

mask_sum 247


In [43]:
dx /= mask.sum()
dx *= mask[:, np.newaxis]

In [44]:
dx.shape

(250, 100)

In [45]:
dx = dx.reshape((N, T, V))
dx.shape

(10, 25, 100)